# APM2 Default Policy
#
# This is the default policy shipped with APM2. It follows a strict
# default-deny model where all actions must be explicitly allowed.
#
# IMPORTANT: This policy is restrictive by design. Customize for your
# use case by creating a project-specific policy file.

policy:
  version: "1.0.0"
  name: "apm2-default"
  description: "Default deny-all policy for APM2"

  rules:
    # ========================================================================
    # FILESYSTEM RULES
    # ========================================================================

    # Allow reading from workspace (current directory and subdirectories)
    - id: "fs-read-workspace"
      type: filesystem
      paths:
        - "./**"
      decision: allow
      reason: "Allow reading workspace files"
      rationale_code: "FS_READ_WORKSPACE"

    # ========================================================================
    # TOOL RULES
    # ========================================================================

    # Allow read-only filesystem operations
    - id: "tool-fs-read"
      type: tool_allow
      tool: "fs.read"
      paths:
        - "./**"
      decision: allow
      reason: "Allow reading workspace files via fs.read tool"

    # Allow glob/search operations
    - id: "tool-fs-glob"
      type: tool_allow
      tool: "fs.glob"
      paths:
        - "./**"
      decision: allow
      reason: "Allow searching workspace files"

    # Allow grep/search operations
    - id: "tool-fs-grep"
      type: tool_allow
      tool: "fs.grep"
      paths:
        - "./**"
      decision: allow
      reason: "Allow searching file contents"

    # ========================================================================
    # BUDGET RULES
    # ========================================================================

    # Token budget for inference calls (100K tokens)
    - id: "budget-tokens"
      type: budget
      budget_type: token
      limit: 100000
      decision: allow
      reason: "Default token budget"

    # Time budget (1 hour)
    - id: "budget-time"
      type: budget
      budget_type: time
      limit: 3600000
      decision: allow
      reason: "Default time budget (1 hour in milliseconds)"

    # Tool call budget (1000 calls)
    - id: "budget-tool-calls"
      type: budget
      budget_type: tool_calls
      limit: 1000
      decision: allow
      reason: "Default tool call budget"

  # Default decision: DENY everything not explicitly allowed
  default_decision: deny
