routing_profile:
  profile_id: local
  description: Local development routing profile for running pipeline stages on local infrastructure with remote fallbacks.
  version: "2026-01-26"
  stages:
    ccp_build:
      provider: local
      timeout_ms: 30000
      retry_policy:
        max_retries: 2
        initial_delay_ms: 500
        backoff_multiplier: 1.5
    impact_map:
      provider: anthropic
      model: claude-3-5-sonnet
      timeout_ms: 60000
      retry_policy:
        max_retries: 3
        initial_delay_ms: 1000
        backoff_multiplier: 2.0
    rfc_frame:
      provider: anthropic
      model: claude-3-5-sonnet
      timeout_ms: 120000
      retry_policy:
        max_retries: 3
        initial_delay_ms: 1000
        backoff_multiplier: 2.0
    ticket_emit:
      provider: anthropic
      model: claude-3-5-sonnet
      timeout_ms: 90000
      retry_policy:
        max_retries: 3
        initial_delay_ms: 1000
        backoff_multiplier: 2.0
    review:
      provider: anthropic
      model: claude-3-5-sonnet
      timeout_ms: 180000
      retry_policy:
        max_retries: 2
        initial_delay_ms: 2000
        backoff_multiplier: 2.0
  fallback:
    provider: local
    timeout_ms: 60000
    reason: Use local fallback when remote providers are unavailable or rate-limited.
