// This file is @generated by prost-build.
/// CTR-PROTO-001: Handshake
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Hello {
    #[prost(uint32, tag = "1")]
    pub protocol_version: u32,
    #[prost(message, optional, tag = "2")]
    pub client_info: ::core::option::Option<ClientInfo>,
    #[prost(string, repeated, tag = "3")]
    pub requested_caps: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct HelloAck {
    #[prost(message, optional, tag = "1")]
    pub server_info: ::core::option::Option<ServerInfo>,
    #[prost(string, repeated, tag = "2")]
    pub granted_caps: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(bytes = "vec", tag = "3")]
    pub policy_hash: ::prost::alloc::vec::Vec<u8>,
    #[prost(btree_map = "string, uint32", tag = "4")]
    pub canonicalizer_versions: ::prost::alloc::collections::BTreeMap<
        ::prost::alloc::string::String,
        u32,
    >,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ClientInfo {
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub version: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ServerInfo {
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub version: ::prost::alloc::string::String,
}
/// CTR-PROTO-002: Episode Control
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CreateEpisode {
    #[prost(bytes = "vec", tag = "1")]
    pub envelope_hash: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct EpisodeCreated {
    #[prost(string, tag = "1")]
    pub episode_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub session_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct StartEpisode {
    #[prost(string, tag = "1")]
    pub episode_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct EpisodeStarted {
    #[prost(uint32, tag = "1")]
    pub session_pid: u32,
    #[prost(string, tag = "2")]
    pub io_stream_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct StopEpisode {
    #[prost(string, tag = "1")]
    pub episode_id: ::prost::alloc::string::String,
    #[prost(enumeration = "StopReason", tag = "2")]
    pub reason: i32,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct EpisodeStopped {
    #[prost(enumeration = "TerminationClass", tag = "1")]
    pub termination_class: i32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SignalEpisode {
    #[prost(string, tag = "1")]
    pub episode_id: ::prost::alloc::string::String,
    #[prost(int32, tag = "2")]
    pub signal: i32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ResizePty {
    #[prost(string, tag = "1")]
    pub episode_id: ::prost::alloc::string::String,
    #[prost(uint32, tag = "2")]
    pub cols: u32,
    #[prost(uint32, tag = "3")]
    pub rows: u32,
}
/// Minimal v1 vocabulary for evidence economics
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct EpisodeQuarantined {
    #[prost(string, tag = "1")]
    pub episode_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub reason: ::prost::alloc::string::String,
    #[prost(bytes = "vec", repeated, tag = "3")]
    pub evidence_pinned: ::prost::alloc::vec::Vec<::prost::alloc::vec::Vec<u8>>,
}
/// CTR-PROTO-003: I/O
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SendInput {
    #[prost(string, tag = "1")]
    pub episode_id: ::prost::alloc::string::String,
    #[prost(bytes = "vec", tag = "2")]
    pub data: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct StreamOutput {
    #[prost(bytes = "vec", tag = "1")]
    pub chunk: ::prost::alloc::vec::Vec<u8>,
    #[prost(enumeration = "StreamKind", tag = "2")]
    pub kind: i32,
    #[prost(uint64, tag = "3")]
    pub seq: u64,
    #[prost(uint64, tag = "4")]
    pub ts: u64,
}
/// CTR-PROTO-004: Tool Mediation
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ToolRequest {
    #[prost(string, tag = "1")]
    pub episode_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub request_id: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub tool: ::prost::alloc::string::String,
    #[prost(bytes = "vec", tag = "4")]
    pub dedupe_key: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", tag = "5")]
    pub args_hash: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", optional, tag = "6")]
    pub inline_args: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ToolDecision {
    #[prost(string, tag = "1")]
    pub request_id: ::prost::alloc::string::String,
    #[prost(enumeration = "DecisionType", tag = "2")]
    pub decision: i32,
    #[prost(string, optional, tag = "3")]
    pub rule_id: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(bytes = "vec", tag = "4")]
    pub policy_hash: ::prost::alloc::vec::Vec<u8>,
    #[prost(message, optional, tag = "5")]
    pub budget_delta: ::core::option::Option<BudgetDelta>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ToolResult {
    #[prost(string, tag = "1")]
    pub request_id: ::prost::alloc::string::String,
    #[prost(enumeration = "ToolOutcome", tag = "2")]
    pub outcome: i32,
    #[prost(bytes = "vec", tag = "3")]
    pub result_hash: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", optional, tag = "4")]
    pub inline_result: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct BudgetDelta {
    #[prost(uint64, tag = "1")]
    pub tokens: u64,
    #[prost(uint32, tag = "2")]
    pub tool_calls: u32,
    #[prost(uint64, tag = "3")]
    pub cpu_ms: u64,
}
/// CTR-PROTO-005: Telemetry
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TelemetryFrame {
    #[prost(string, tag = "1")]
    pub episode_id: ::prost::alloc::string::String,
    #[prost(uint64, tag = "2")]
    pub seq: u64,
    #[prost(uint64, tag = "3")]
    pub ts_mono: u64,
    #[prost(uint64, tag = "4")]
    pub cpu_ns: u64,
    #[prost(uint64, tag = "5")]
    pub mem_rss_bytes: u64,
    #[prost(uint64, tag = "6")]
    pub io_read_bytes: u64,
    #[prost(uint64, tag = "7")]
    pub io_write_bytes: u64,
    #[prost(message, optional, tag = "8")]
    pub cgroup_stats: ::core::option::Option<CgroupStats>,
    #[prost(uint32, tag = "9")]
    pub o11y_flags: u32,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct CgroupStats {
    #[prost(uint64, tag = "1")]
    pub cpu_usage_usec: u64,
    #[prost(uint64, tag = "2")]
    pub memory_current: u64,
    #[prost(uint64, tag = "3")]
    pub memory_max: u64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TelemetryPolicy {
    #[prost(uint64, tag = "1")]
    pub sample_period_ms: u64,
    #[prost(message, repeated, tag = "2")]
    pub promote_triggers: ::prost::alloc::vec::Vec<PromoteTrigger>,
    #[prost(message, optional, tag = "3")]
    pub ring_buffer_limits: ::core::option::Option<RingBufferLimits>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PromoteTrigger {
    #[prost(string, tag = "1")]
    pub metric: ::prost::alloc::string::String,
    #[prost(double, tag = "2")]
    pub threshold: f64,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct RingBufferLimits {
    #[prost(uint64, tag = "1")]
    pub max_pty_bytes: u64,
    #[prost(uint64, tag = "2")]
    pub max_tool_bytes: u64,
    #[prost(uint64, tag = "3")]
    pub max_tel_frames: u64,
}
/// CTR-PROTO-006: Receipts and Evidence
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PublishEvidence {
    #[prost(bytes = "vec", tag = "1")]
    pub artifact_hash: ::prost::alloc::vec::Vec<u8>,
    #[prost(enumeration = "EvidenceKind", tag = "2")]
    pub kind: i32,
    #[prost(enumeration = "RetentionHint", tag = "3")]
    pub retention_hint: i32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Receipt {
    #[prost(enumeration = "ReceiptKind", tag = "1")]
    pub kind: i32,
    #[prost(bytes = "vec", tag = "2")]
    pub unsigned_bytes_hash: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", tag = "3")]
    pub signature: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", repeated, tag = "4")]
    pub evidence_refs: ::prost::alloc::vec::Vec<::prost::alloc::vec::Vec<u8>>,
    #[prost(bytes = "vec", tag = "5")]
    pub policy_hash: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", tag = "6")]
    pub envelope_hash: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, optional, tag = "7")]
    pub issuer_id: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(bytes = "vec", optional, tag = "8")]
    pub issuer_signature: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
}
/// Minimal v1 vocabulary events for evidence economics
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct EvidencePinned {
    #[prost(bytes = "vec", tag = "1")]
    pub artifact_hash: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, tag = "2")]
    pub reason: ::prost::alloc::string::String,
    #[prost(string, optional, tag = "3")]
    pub defect_id: ::core::option::Option<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct EvidenceTtlExpired {
    #[prost(bytes = "vec", tag = "1")]
    pub artifact_hash: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, tag = "2")]
    pub timestamp: u64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CompactionCompleted {
    #[prost(bytes = "vec", tag = "1")]
    pub summary_receipt_hash: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", repeated, tag = "2")]
    pub tombstoned_hashes: ::prost::alloc::vec::Vec<::prost::alloc::vec::Vec<u8>>,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum StopReason {
    Unspecified = 0,
    GoalSatisfied = 1,
    BudgetExhausted = 2,
    PolicyViolation = 3,
    UserRequest = 4,
    HarnessCrash = 5,
    AdapterFailure = 6,
}
impl StopReason {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "STOP_REASON_UNSPECIFIED",
            Self::GoalSatisfied => "GOAL_SATISFIED",
            Self::BudgetExhausted => "BUDGET_EXHAUSTED",
            Self::PolicyViolation => "POLICY_VIOLATION",
            Self::UserRequest => "USER_REQUEST",
            Self::HarnessCrash => "HARNESS_CRASH",
            Self::AdapterFailure => "ADAPTER_FAILURE",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "STOP_REASON_UNSPECIFIED" => Some(Self::Unspecified),
            "GOAL_SATISFIED" => Some(Self::GoalSatisfied),
            "BUDGET_EXHAUSTED" => Some(Self::BudgetExhausted),
            "POLICY_VIOLATION" => Some(Self::PolicyViolation),
            "USER_REQUEST" => Some(Self::UserRequest),
            "HARNESS_CRASH" => Some(Self::HarnessCrash),
            "ADAPTER_FAILURE" => Some(Self::AdapterFailure),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum TerminationClass {
    Unspecified = 0,
    CleanExit = 1,
    ErrorExit = 2,
    Quarantined = 3,
}
impl TerminationClass {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "TERMINATION_CLASS_UNSPECIFIED",
            Self::CleanExit => "CLEAN_EXIT",
            Self::ErrorExit => "ERROR_EXIT",
            Self::Quarantined => "QUARANTINED",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "TERMINATION_CLASS_UNSPECIFIED" => Some(Self::Unspecified),
            "CLEAN_EXIT" => Some(Self::CleanExit),
            "ERROR_EXIT" => Some(Self::ErrorExit),
            "QUARANTINED" => Some(Self::Quarantined),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum StreamKind {
    Stdout = 0,
    Stderr = 1,
}
impl StreamKind {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Stdout => "STDOUT",
            Self::Stderr => "STDERR",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "STDOUT" => Some(Self::Stdout),
            "STDERR" => Some(Self::Stderr),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum DecisionType {
    Allow = 0,
    Deny = 1,
    DedupeHit = 2,
}
impl DecisionType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Allow => "ALLOW",
            Self::Deny => "DENY",
            Self::DedupeHit => "DEDUPE_HIT",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "ALLOW" => Some(Self::Allow),
            "DENY" => Some(Self::Deny),
            "DEDUPE_HIT" => Some(Self::DedupeHit),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum ToolOutcome {
    Unspecified = 0,
    Success = 1,
    Failure = 2,
    Error = 3,
}
impl ToolOutcome {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "TOOL_OUTCOME_UNSPECIFIED",
            Self::Success => "SUCCESS",
            Self::Failure => "FAILURE",
            Self::Error => "ERROR",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "TOOL_OUTCOME_UNSPECIFIED" => Some(Self::Unspecified),
            "SUCCESS" => Some(Self::Success),
            "FAILURE" => Some(Self::Failure),
            "ERROR" => Some(Self::Error),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum ReceiptKind {
    ToolExecution = 0,
    EpisodeStart = 1,
    EpisodeStop = 2,
    Gate = 3,
    Telemetry = 4,
    Compaction = 5,
    StopOrder = 6,
}
impl ReceiptKind {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::ToolExecution => "TOOL_EXECUTION",
            Self::EpisodeStart => "EPISODE_START",
            Self::EpisodeStop => "EPISODE_STOP",
            Self::Gate => "GATE",
            Self::Telemetry => "TELEMETRY",
            Self::Compaction => "COMPACTION",
            Self::StopOrder => "STOP_ORDER",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "TOOL_EXECUTION" => Some(Self::ToolExecution),
            "EPISODE_START" => Some(Self::EpisodeStart),
            "EPISODE_STOP" => Some(Self::EpisodeStop),
            "GATE" => Some(Self::Gate),
            "TELEMETRY" => Some(Self::Telemetry),
            "COMPACTION" => Some(Self::Compaction),
            "STOP_ORDER" => Some(Self::StopOrder),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum EvidenceKind {
    Unspecified = 0,
    PtyTranscript = 1,
    ToolIo = 2,
    TelemetryRaw = 3,
    AdapterFailure = 4,
    IncidentSnapshot = 5,
}
impl EvidenceKind {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "EVIDENCE_KIND_UNSPECIFIED",
            Self::PtyTranscript => "EVIDENCE_KIND_PTY_TRANSCRIPT",
            Self::ToolIo => "EVIDENCE_KIND_TOOL_IO",
            Self::TelemetryRaw => "EVIDENCE_KIND_TELEMETRY_RAW",
            Self::AdapterFailure => "EVIDENCE_KIND_ADAPTER_FAILURE",
            Self::IncidentSnapshot => "EVIDENCE_KIND_INCIDENT_SNAPSHOT",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "EVIDENCE_KIND_UNSPECIFIED" => Some(Self::Unspecified),
            "EVIDENCE_KIND_PTY_TRANSCRIPT" => Some(Self::PtyTranscript),
            "EVIDENCE_KIND_TOOL_IO" => Some(Self::ToolIo),
            "EVIDENCE_KIND_TELEMETRY_RAW" => Some(Self::TelemetryRaw),
            "EVIDENCE_KIND_ADAPTER_FAILURE" => Some(Self::AdapterFailure),
            "EVIDENCE_KIND_INCIDENT_SNAPSHOT" => Some(Self::IncidentSnapshot),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum RetentionHint {
    Unspecified = 0,
    Ephemeral = 1,
    Standard = 2,
    Archival = 3,
}
impl RetentionHint {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "RETENTION_HINT_UNSPECIFIED",
            Self::Ephemeral => "EPHEMERAL",
            Self::Standard => "STANDARD",
            Self::Archival => "ARCHIVAL",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "RETENTION_HINT_UNSPECIFIED" => Some(Self::Unspecified),
            "EPHEMERAL" => Some(Self::Ephemeral),
            "STANDARD" => Some(Self::Standard),
            "ARCHIVAL" => Some(Self::Archival),
            _ => None,
        }
    }
}
